version: '3.8'

services:
  frontend:
    image: ${DOCKERHUB_USER}/${PROJECT_NAME}-frontend:arm
    platform: ${ARCHITECTURE}
    ports:
      - ${FRONTEND_CONTAINER_PORT}:8080
    depends_on:
      - backend
    networks:
      - tay-training-network

  backend:
    image: ${DOCKERHUB_USER}/${PROJECT_NAME}-backend:arm
    platform: ${ARCHITECTURE}
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - ./tay-training-backend/.env.production
    ports:
      - ${BACKEND_CONTAINER_PORT}:3000
    volumes:
      - .:/usr/src/app
    networks:
      - tay-training-network

  db:
    image: ${DOCKERHUB_USER}/${PROJECT_NAME}-db:arm
    platform: ${ARCHITECTURE}
    restart: always
    ports:
      - ${DB_CONTAINER_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      POSTGRES_DB: mydb
    volumes:
      - tay-training-db-data:/var/lib/postgresql/data
    networks:
      - tay-training-network

volumes:
  tay-training-db-data:
networks:
  tay-training-network:





